name: Compile and deploy
on:
  push:
    branches:
      - main
jobs:
  buildndeploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive texlive-base texlive-full texlive-science build-essential
          version: 1.0
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
