name: Compile and deploy
on:
  push:
    branches:
      - main
jobs:
  buildndeploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache and Install apt (.deb) Packages
        uses: eth-pkg/apt-deb-cache@v0.2.6
        with:
          packages: 'texlive texlive-base texlive-full texlive-science build-essential'

      - run: make

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
